import { useEffect, useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { api, json } from './api'
import { usePreferences } from './i18n'
import { views, FramingGuide } from './photos'

type Template={id:string;name:string;version:number;questions:{id:string;label:string;required:boolean}[]}
type UploadLink={id:string;title:string;photoSetId:string;consultationId:string;expiresAt:string;revokedAt:string|null;submittedAt:string|null;reviewedAt:string|null}
export type Reminder={id:string;clientId:string;clientName:string;title:string;message:string;dueAt:string;clientVisible:boolean;status:string;version:number;due:boolean}
type Portal={title:string;expiresAt:string;template:Template|null;views:Record<string,string>;missing:string[];intake:{fields:{goal:string;maintenance:string;routine:string;likes:string;dislikes:string};answers:Record<string,string>}|null;reviewedAt:string|null;notice:string;reminders:Reminder[]}
async function portalRequest<T>(token:string,path='',options?:RequestInit):Promise<T>{
 const response=await fetch('/api/client-upload'+path,{...options,credentials:'omit',headers:{...options?.headers,Authorization:'Bearer '+token}})
 if(!response.ok){let message=`Request failed (${response.status})`;try{message=(await response.json()).error||message}catch{};throw new Error(message)}
 return response.json() as Promise<T>
}
function PortalPhoto({token,view,asset}:{token:string;view:string;asset:string}){
 const [url,setURL]=useState(''),[error,setError]=useState('');const {t}=usePreferences()
 useEffect(()=>{let active=true,object='';setURL('');setError('');fetch('/api/client-upload/photos/'+view,{credentials:'omit',headers:{Authorization:'Bearer '+token}}).then(async r=>{if(!r.ok)throw new Error('Photo unavailable');object=URL.createObjectURL(await r.blob());if(active)setURL(object);else URL.revokeObjectURL(object)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false;if(object)URL.revokeObjectURL(object)}},[token,view,asset])
 return url?<img className="slot-photo" src={url} alt={t(views.find(v=>v.id===view)!.name)}/>:<p>{t(error||'Loading…')}</p>
}
export function ClientUploadPortal(){
 const {t}=usePreferences(),cache=useQueryClient(),[token]=useState(()=>window.location.hash.slice(1)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const portal=useQuery({queryKey:['client-upload-portal',token],queryFn:()=>portalRequest<Portal>(token),enabled:!!token,refetchInterval:10000})
 const [goal,setGoal]=useState(''),[maintenance,setMaintenance]=useState(''),[routine,setRoutine]=useState(''),[likes,setLikes]=useState(''),[dislikes,setDislikes]=useState(''),[answers,setAnswers]=useState<Record<string,string>>({})
 const [pending,setPending]=useState<{view:string;file:File;url:string;expected:string;ready:boolean}>()
 useEffect(()=>()=>{if(pending)URL.revokeObjectURL(pending.url)},[pending?.url])
 useEffect(()=>{if(portal.error)setPending(undefined)},[portal.error])
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{await portalRequest(token,'/intake',json('POST',{goal,maintenance,routine,likes,dislikes,answers}));await cache.invalidateQueries({queryKey:['client-upload-portal',token]});setMessage('Intake submitted for professional review.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function choose(view:string,file?:File){if(!file)return;setError('');setMessage('');if(file.size>10*1024*1024){setError('image must be at most 10 MB');return}setPending({view,file,url:URL.createObjectURL(file),expected:portal.data?.views[view]||'',ready:false})}
 async function upload(){if(!pending?.ready)return;setBusy(true);setError('');try{const body=new FormData();body.append('image',pending.file);body.append('expectedAssetId',pending.expected);await portalRequest(token,'/photos/'+pending.view,{method:'POST',body});setPending(undefined);setMessage('Photo saved to the labeled view. Earlier photos remain in the gallery.');await cache.invalidateQueries({queryKey:['client-upload-portal',token]})}catch(e){setError((e as Error).message);await cache.invalidateQueries({queryKey:['client-upload-portal',token]})}finally{setBusy(false)}}
 const p=portal.data
 return <main className="page client-upload-portal"><div className="brand"><span className="brand-mark">T</span>trama</div><h1>{t('Your private intake and photo upload')}</h1><p>{t('No client account is needed. Keep this access link private. Ask your professional to remove a photo, withdraw permission or delete your journey.')}</p>
 {!token?<p role="alert">{t('Open the complete private link supplied by your professional.')}</p>:portal.error?<p className="error" role="alert">{t(portal.error.message)}</p>:portal.isPending?<p>{t('Loading…')}</p>:p&&<>
 <h2>{p.title}</h2><p>{t('Link expires')}: {new Date(p.expiresAt).toLocaleString()}</p><details><summary>{t('Your image permission')}</summary><p>{t(p.notice)}</p></details>
 <section className="card"><h2>{t('Your goals and routine')}</h2>{p.intake?<><p role="status">{t(p.reviewedAt?'Professional reviewed this intake.':'Intake submitted for professional review.')}</p><dl><dt>{t('Client goal')}</dt><dd>{p.intake.fields.goal}</dd><dt>{t('Maintenance tolerance')}</dt><dd>{t(p.intake.fields.maintenance)}</dd><dt>{t('Daily routine')}</dt><dd>{p.intake.fields.routine}</dd></dl>{p.template?.questions.map(q=><p key={q.id}><strong>{q.label}: </strong>{p.intake!.answers[q.id]}</p>)}<p>{t('Ask your professional to record corrections as a new consultation revision.')}</p></>:<form onSubmit={submit} className="stack-form"><label>{t('Client goal')}<textarea aria-label={t('Client goal')} value={goal} onChange={e=>setGoal(e.target.value)} maxLength={4000} required/></label><label>{t('Maintenance tolerance')}<select aria-label={t('Maintenance tolerance')} value={maintenance} onChange={e=>setMaintenance(e.target.value)} required><option value="">{t('Choose tolerance')}</option>{['low','moderate','high'].map(v=><option key={v} value={v}>{t(v)}</option>)}</select></label><label>{t('Daily routine')}<textarea value={routine} onChange={e=>setRoutine(e.target.value)} maxLength={4000}/></label><label>{t('What you like')}<textarea value={likes} onChange={e=>setLikes(e.target.value)} maxLength={4000}/></label><label>{t('What you dislike')}<textarea value={dislikes} onChange={e=>setDislikes(e.target.value)} maxLength={4000}/></label>{p.template?.questions.map(q=><label key={q.id}>{q.label}<textarea aria-label={q.label} value={answers[q.id]||''} required={q.required} maxLength={4000} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/></label>)}<button className="button primary" disabled={busy}>{t('Submit intake for review')}</button></form>}</section>
 <section className="card capture-panel"><h2>{t('Six views, one consistent baseline')}</h2><p>{t('Use a steady camera at head height, even light and a plain background. Keep the full hair and beard outline inside the frame.')}</p><p>{t('Left and right refer to the client’s own sides. Avoid mirrored selfies, filters and cropped hair or beard. Review each view and retake blurred photos.')}</p><p role="status">{6-p.missing.length}/6 {t('main views uploaded')} · {p.missing.length?t('Incomplete set; you can continue with missing views.'):t('Six labeled views present; check coverage and sharpness yourself.')}</p>
 {pending&&<div className="photo-review"><h3>{t('Review before saving')}: {t(views.find(v=>v.id===pending.view)!.name)}</h3><img src={pending.url} alt={t('Selected upload for review')} onLoad={()=>setPending(v=>v?{...v,ready:true}:v)} onError={()=>{setPending(undefined);setError('This image cannot be read. Choose a valid JPEG, PNG or WebP.')}}/><p>{t('Check the angle, sharpness and full outline. To retake, cancel and choose another photo.')}</p><button className="button primary" disabled={busy||!pending.ready} onClick={upload}>{t('Save labeled photo')}</button><button className="button ghost" disabled={busy} onClick={()=>setPending(undefined)}>{t('Cancel')}</button></div>}
 <div className="photo-slot-grid">{views.map((v,i)=><article className="photo-slot" key={v.id}><h3>{t(v.name)} <small>{t(i<6?'Main view':'Optional detail')}</small></h3>{p.views[v.id]?<PortalPhoto token={token} view={v.id} asset={p.views[v.id]}/>:<FramingGuide view={v.id}/>}<p>{t(v.hint)}</p><label className="button secondary photo-input">{t(p.views[v.id]?'Review a replacement':'Choose photo')}<input aria-label={`${t('Upload')}: ${t(v.name)}`} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!!pending} onChange={e=>{choose(v.id,e.target.files?.[0]);e.target.value=''}}/></label></article>)}</div></section>
 <section className="card"><h2>{t('Reminders from your professional')}</h2>{p.reminders.length?p.reminders.map(v=><article key={v.id}><h3>{v.title}</h3><p>{new Date(v.dueAt).toLocaleString()} · {t(v.due?'Due now':'Upcoming')}</p><p>{v.message}</p></article>):<p>{t('No pending reminders.')}</p>}</section></>}
 {message&&<p role="status">{t(message)}</p>}{error&&<p role="alert" className="error">{t(error)}</p>}</main>
}
export function ClientUploadPanel({clientId,authorized}:{clientId:string;authorized:boolean}){
 const {t}=usePreferences(),cache=useQueryClient(),base=`/clients/${clientId}`
 const links=useQuery({queryKey:['upload-links',clientId],queryFn:()=>api<UploadLink[]>(base+'/upload-links'),refetchInterval:8000})
 const templates=useQuery({queryKey:['intake-templates'],queryFn:()=>api<(Template&{archived:boolean})[]>('/intake-templates')})
 const reminders=useQuery({queryKey:['reminders',clientId],queryFn:()=>api<Reminder[]>(base+'/reminders'),refetchInterval:15000})
 const [title,setTitle]=useState(''),[hours,setHours]=useState(24),[template,setTemplate]=useState(''),[path,setPath]=useState(''),[reminderTitle,setReminderTitle]=useState(''),[message,setMessage]=useState(''),[due,setDue]=useState(''),[visible,setVisible]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await cache.invalidateQueries()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function link(e:FormEvent){e.preventDefault();await action(async()=>{const result=await api<{path:string}>(base+'/upload-links',json('POST',{title,hours,templateId:template,templateVersion:templates.data?.find(v=>v.id===template)?.version||0}));setPath(result.path);setTitle('')})}
 async function reminder(e:FormEvent){e.preventDefault();await action(async()=>{await api(base+'/reminders',json('POST',{title:reminderTitle,message,dueAt:new Date(due).toISOString(),clientVisible:visible}));setReminderTitle('');setMessage('')})}
 return <section className="card" id="client-self-upload"><h2>{t('Client self-upload and reminders')}</h2><p>{t('Create a private link for a new intake and photo set. The client can see only that submission and client-visible reminders. Expiry, revocation and withdrawal stop access.')}</p><details><summary>{t('Create client upload link')}</summary><form onSubmit={link} className="stack-form"><label>{t('Upload invitation title')}<input value={title} onChange={e=>setTitle(e.target.value)} minLength={2} maxLength={160} required/></label><label>{t('Link expiry (hours)')}<input type="number" value={hours} min={1} max={168} onChange={e=>setHours(Number(e.target.value))}/></label><label>{t('Intake template')}<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="">{t('No template')}</option>{templates.data?.filter(v=>!v.archived).map(v=><option key={v.id} value={v.id}>{v.name} / {v.version}</option>)}</select></label><button className="button primary" disabled={busy||!authorized}>{t('Create private upload link')}</button></form>{path&&authorized&&<div className="notice"><p>{t('This private access link is displayed only now. Copy it before leaving. A new link creates a separate submission.')}</p><a href={path} target="_blank" rel="noreferrer">{t('Open client upload portal')}</a><input aria-label={t('Private client upload link')} value={window.location.origin+path} readOnly/></div>}</details>
 <ul>{links.data?.map(v=><li key={v.id}><strong>{v.title}</strong> · {new Date(v.expiresAt).toLocaleString()} · {t(v.revokedAt?'Revoked':new Date(v.expiresAt)<new Date()?'Expired':'Active')} {v.submittedAt&&<><span> · {t(v.reviewedAt?'Reviewed':'Awaiting intake review')}</span><button className="button ghost" disabled={busy||!authorized||!!v.reviewedAt} onClick={()=>action(()=>api(base+`/upload-links/${v.id}/review`,json('POST',{})))}>{t('Mark intake reviewed')}</button></>}{!v.revokedAt&&<button className="button ghost" disabled={busy} onClick={()=>action(()=>api(base+`/upload-links/${v.id}/revoke`,json('POST',{})))}>{t('Revoke upload link')}</button>}</li>)}</ul>
 <details><summary>{t('Add local reminder')}</summary><form onSubmit={reminder} className="stack-form"><label>{t('Reminder title')}<input value={reminderTitle} onChange={e=>setReminderTitle(e.target.value)} minLength={2} maxLength={160} required/></label><label>{t('Reminder guidance')}<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000}/></label><label>{t('Reminder due')}<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} required/></label><label className="check-label"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/>{t('Visible in the private client portal')}</label><button className="button primary" disabled={busy||!authorized}>{t('Retain reminder')}</button></form></details>
 <p>{t('Reminders are shown locally. No email, SMS or notification has been sent.')}</p><ul>{reminders.data?.map(v=><li key={v.id}><strong>{v.title}</strong> · {new Date(v.dueAt).toLocaleString()} · {t(v.status==='pending'?(v.due?'Due now':'Upcoming'):v.status)}<p>{v.message}</p>{v.status==='pending'&&['completed','dismissed'].map(status=><button key={status} className="button ghost" disabled={busy||!authorized} onClick={()=>action(()=>api(base+`/reminders/${v.id}`,json('PATCH',{version:v.version,status})))}>{t(status==='completed'?'Complete reminder':'Dismiss reminder')}</button>)}</li>)}</ul>
 {(error||links.error||reminders.error||templates.error)&&<p className="error" role="alert">{t(error||links.error?.message||reminders.error?.message||templates.error?.message||'')}</p>}</section>
}
export function ReminderQueue(){const {t}=usePreferences();const q=useQuery({queryKey:['reminder-queue'],queryFn:()=>api<Reminder[]>('/reminders'),refetchInterval:30000});return <section className="card"><h2>{t('Studio reminder queue')}</h2>{q.error?<p role="alert">{q.error.message}</p>:q.data?.filter(r=>r.status==='pending').length?<ul>{q.data.filter(r=>r.status==='pending').map(r=><li key={r.id}><a href={`/clients/${r.clientId}#client-self-upload`}>{r.clientName}: {r.title}</a> · {new Date(r.dueAt).toLocaleString()} · {t(r.due?'Due now':'Upcoming')}</li>)}</ul>:<p>{t('No pending reminders.')}</p>}</section>}
