import type { DemoJob, DemoLibrary, DemoOption } from './demo-types'
import { usePreferences } from './i18n'
const terms:Record<string,{version:string;software:string;model:string;url:string;modelURL?:string}>={
 'blender-mpfb':{version:'Blender 5.2.1 LTS / MPFB 2.0.17',software:'GPL-3.0',model:'MakeHuman core CC0-1.0',url:'https://www.blender.org/about/license/',modelURL:'https://static.makehumancommunity.org/about/license.html'},
 colmap:{version:'PyCOLMAP 4.2.1 CPU',software:'BSD-3-Clause + dependency notices',model:'No pretrained head model',url:'https://github.com/colmap/colmap/blob/4.2.1/COPYING.txt'},
 meshroom:{version:'Meshroom 2025.1.0 / AliceVision 3.3.0 source',software:'MPL-2.0; runtime CUDA terms pending',model:'No native reconstruction acquired',url:'https://github.com/alicevision/Meshroom/blob/v2025.1.0/LICENSE-MPL2.md',modelURL:'https://docs.nvidia.com/cuda/archive/12.1.1/eula/index.html'},
 makehuman:{version:'MakeHuman 1.3.0',software:'AGPL-3.0-or-later',model:'CC0 core data; output exception',url:'https://static.makehumancommunity.org/about/license.html'},
 flame:{version:'FLAME 2023 Open / neutral rig v4',software:'Original GPL-3.0 NumPy fitting code',model:'CC-BY-4.0 + published usage restrictions',url:'https://flame.is.tue.mpg.de/modellicense.html',modelURL:'https://doi.org/10.1145/3130800.3130813'},
 open3d:{version:'Open3D CPU 0.20.0',software:'MIT + dependency notices',model:'Retains upstream model obligations',url:'https://github.com/isl-org/Open3D/blob/v0.20.0/LICENSE'},
 meshlab:{version:'PyMeshLab 2025.7.post1 / MeshLab 2025.07d',software:'GPL-3.0 combined route',model:'Retains upstream model obligations',url:'https://github.com/cnr-isti-vclab/PyMeshLab/blob/v2025.7.post1/LICENSE'},
 cloudcompare:{version:'CloudCompare 2.13.2',software:'GPL-3.0-or-later combined build',model:'Retains upstream model obligations',url:'https://github.com/CloudCompare/CloudCompare/blob/49dbbb662f296c7780aae717897c85b3cb3764ed/license.txt'},
}
export function currentNativeJob(j:DemoJob){
 if(j.status!=='completed'||!j.result.head||j.result.catalog?.version!=='trama-surface-styles-v1')return false
 const fit:Record<string,string>={'blender-mpfb':'mpfb-metre-z-up-v2',makehuman:'makehuman-metre-z-up-v2',flame:'flame-2023-open-neutral-rig-v4'}
 if(fit[j.candidate])return j.result.fit?.basisVersion===fit[j.candidate]&&j.result.targetBasisCheck?.passed!==false&&(j.candidate!=='makehuman'||j.result.nativeShape?.styleAttachment?.version==='makehuman-visible-lips-v2')
 const component:Record<string,string>={open3d:'open3d-cpu-upstream-v5',meshlab:'meshlab-native-upstream-v1',cloudcompare:'cloudcompare-native-upstream-v2'}
 return j.result.component?.processingVersion===component[j.candidate]
}
export function DemoReview({library,jobs,options,choose}:{library:DemoLibrary;jobs:DemoJob[];options:DemoOption[];choose:(id:string)=>void}){
 const {t}=usePreferences()
 return <section className="card demo-review" id="candidate-review"><h2>{t('Eight-candidate local comparison')}</h2><p>{t('This table reports retained experiments for the selected fictional client. Technical workflow checks do not establish real-person likeness, measured hidden geometry or professional acceptance. All alternatives remain available.')}</p>
 <p>{t('Shared catalog')}: {library.hair.filter(s=>!s.deprecated).length} {t('hairstyles')} / {library.beard.filter(s=>!s.deprecated).length} {t('beardstyles')} · {t('Original procedural assets: CC0-1.0; generator code licensed separately.')}</p>
 <div className="table-wrap"><table><thead><tr><th>{t('Candidate and role')}</th><th>{t('Observed local result')}</th><th>{t('Processing effort and retained size')}</th><th>{t('Software and model terms')}</th></tr></thead><tbody>{library.candidates.map(c=>{
 const records=jobs.filter(j=>j.candidate===c.id),valid=records.filter(currentNativeJob),latest=valid[0],failed=records.filter(j=>j.status==='failed'),native=records.filter(j=>j.kind!=='input-check'),license=terms[c.id]
 const sizes=valid.map(j=>(j.result.retainedBytes||0)/1048576),seconds=valid.map(j=>(j.result.elapsedMs||0)/1000),resources=valid.flatMap(j=>j.result.resources||[]),peak=Math.max(0,...resources.map(r=>r.peakRssKiB))/1024
 const explored=options.filter(o=>o.candidate===c.id&&valid.some(j=>j.id===o.state.modelRunId)).length
 return <tr key={c.id}><td><strong>{c.name}</strong><p>{t(c.role)}</p>{c.dependency&&<p>{t(c.dependency)}</p>}<button className="button secondary" onClick={()=>choose(c.id)}>{t('Open workflow')}: {c.name}</button></td><td>{c.id==='meshroom'?<><strong>{t('Blocked: AliceVision runtime terms')}</strong><p>{t('Prepared graph and input checks are setup evidence. No native reconstruction or expected head is available.')}</p></>:c.id==='colmap'?<><strong>{t('Six-photo reconstruction failed')}</strong><p>{failed.length} {t('retained failed experiments')} · {t('No usable registered head; no fallback counted as success.')}</p></>:latest?<><strong>{valid.length} {t('current native experiments')}</strong><p>{!!c.dependency?t('Processed upstream fitted geometry; not standalone photo reconstruction.'):t('Client-specific template fitting; hidden surfaces inferred.')}</p>{latest.result.component&&<p>{t('Upstream route')}: {latest.result.component.upstream.candidate}</p>}<p>{explored} {t('saved native explorations')}</p></>:<p>{t('No current native result retained for this client.')}</p>}<small>{native.length} {t('processing records; older failures and cancelled experiments remain in history.')}</small></td><td>{seconds.length?<><p>{Math.min(...seconds).toFixed(2)}–{Math.max(...seconds).toFixed(2)} s · {Math.min(...sizes).toFixed(1)}–{Math.max(...sizes).toFixed(1)} MiB</p><p>{peak.toFixed(1)} MiB {t('reported peak RSS')}</p><small>{t('Supporting times exclude upstream fitting. RSS measurements include stated process-tree limitations. Retained sizes include original inputs and evaluation files, not browser transfer size.')}</small></>:<p>{t('Native success timing unavailable; inspect retained failure or setup evidence.')}</p>}</td><td><strong>{license.version}</strong><p>{license.software}</p><p>{license.model}</p><a href={license.url} target="_blank" rel="noreferrer">{t('Primary license terms')}</a>{license.modelURL&&<p><a href={license.modelURL} target="_blank" rel="noreferrer">{t('Model or runtime source')}</a></p>}</td></tr>
 })}</tbody></table></div><p className="notice">{t('Observed inputs are photographs and detected 2D features. Fitted or processed template surfaces are not observed 3D scans. Synthetic clients and simulated outcomes demonstrate persistence and editing, not real reconstruction accuracy.')}</p><p>{t('Likeness, clipping, coverage and maintenance suitability require your professional review. Final route selection remains pending.')}</p><a className="button secondary" href="http://127.0.0.1:8765/#task-21" target="_blank" rel="noreferrer">{t('Open local comparison evidence and execution log')}</a></section>
}
